Feature/other locations
womenrising/womenrising pull request #36
Opened 2017-02-24 22:33 UTC by rfjackson11

## Migrations
YES

## Description
Allow users to choose "Other" location, and when they do, they should provide their zipcode.

## Deploy Notes
Requires db migration

## Github Issue
#31 

## Background

`lives_in_detroit` is no longer their for the user to choose, but has not been removed from the code base. We need to make a decision whether to add it back, and have both for a time on staging. Or just agree not to deploy staging to production until we change the code base logic. (Should be the very next PR either way)

## Screenshots

![image](https://cloud.githubusercontent.com/assets/11759443/23323614/8726033e-faa6-11e6-9a88-9029fae32e43.png)

![image](https://cloud.githubusercontent.com/assets/11759443/23323619/9043535e-faa6-11e6-8aa6-8eb4ac74d530.png)

## Definition of Done

- [X] This PR has appropriate test coverage.

2017-02-24 22:35 UTC, rfjackson11 commented
@aelydens @westonplatter I have a question above under Background. Will repost in this comment as well.
`lives_in_detroit` is no longer there for the user to choose, but has not been removed from the code base. We need to make a decision whether to add it back to the view, and have both for a time on staging. Or just agree not to deploy staging to production until we change the code base logic. (Should be the very next PR either way). Which would you both prefer?

2017-02-24 22:35 UTC, rfjackson11 commented
@marshallds would you review?

2017-03-04 17:19 UTC, marshallds requested changes
looks pretty good.  Just one thing...

2017-03-04 17:19 UTC, marshallds commented on db/migrate/20170218190259_add_zip_code_to_user.rb
> +    add_column :users, :zip_code, :integer
zip codes aren't actually scalars.  Storing as an integer will truncade leading zeros for places like Boston (02108 would be stored as 2108)

2017-03-04 17:52 UTC, marshallds approved these changes

2017-04-15 16:44 UTC, merged