Refactor/remove detroit
womenrising/womenrising pull request #40
Opened 2017-04-04 15:06 UTC by rfjackson11

## Migrations
YES

## Description
Group peers based on location

## Github Issue
Fixes #37

## Definition of Done

- [X] This PR has appropriate test coverage.
- ~~[ ] Documentation has been updated. *(if needed)*~~

2017-04-04 15:06 UTC, rfjackson11 commented
@aelydens and @westonplatter can you both please review this?

2017-04-04 15:29 UTC, marshallds commented on spec/models/peer_group_spec.rb
> +        @groups = PeerGroup.all.map(&:users)
I don't think we actually need instance variables...

2017-04-13 15:08 UTC, aelydens commented on app/views/users/edit.html.erb
> +<script>
Probably worth pulling this out of the view and into a separate js file, just to encourage future contributors to follow that pattern.

2017-04-13 15:10 UTC, aelydens commented on app/views/users/edit.html.erb
> +            <h4 class="medium-frame hidden" id="zip-code">Zip Code:
Nice!

2017-04-13 15:11 UTC, aelydens approved these changes
Looks good. Thanks for updating the specs!

2017-04-14 16:15 UTC, westonplatter requested changes

2017-04-14 16:15 UTC, westonplatter commented on app/models/peer_group.rb
> +      location_id: location
What value is stored in `location`, integer or an ActiveRecord instance? If it's the an integer (ie, a Location instance `id`), let's change this to `location_id`.

2017-04-14 16:15 UTC, westonplatter commented on spec/features/user_information_spec.rb
> +  scenario 'can choose other location' do
Nice work on adding specs here!

2017-04-15 16:23 UTC, rfjackson11 commented
@westonplatter I addressed your comment, please re-review

2017-04-15 17:54 UTC, westonplatter commented
@rfjackson11 sweet. looks good to me.

2017-04-15 18:01 UTC, westonplatter approved these changes

2017-04-17 00:35 UTC, merged

2017-04-17 15:27 UTC, westonplatter commented
Great work @rfjackson11!!