WIP Mentor matching waitlist #27
womenrising/womenrising pull request #84
Opened 2017-07-18 17:24 UTC by slague

Hi, I would love some feedback on what I've started doing towards the "waitlist" issue.  As Kate knows, I am a new developer and really want to make a contribution to some open source code, but I'd love to get a little more context before proceeding! Thanks, Stephanie.

@KateCatlin @rfjackson11 @marshallds 

## Migrations
YES 

## Description
I have modified the User model slightly so that there is a mentor scope and mentee scope. A wants_mentor column has been added to the User model. I have written corresponding unit tests.

## Deploy Notes
N/A -- WIP 

## Github Issue
Working on #27

## Background

Any other information you would like to provide for this item, if relevant.

## Screenshots

If this PR includes changes to the view.

## Definition of Done

- [ ] This PR has appropriate test coverage.
- [ ] Documentation has been updated. *(if needed)*

2017-08-10 17:48 UTC, rfjackson11 commented
@marshallds and @slague I have completed this PR, I just need to get the scheduler set up. Please take a look at the code when you get a chance.

2017-08-10 20:13 UTC, mrgenixus requested changes

2017-08-10 20:13 UTC, mrgenixus commented on app/assets/stylesheets/styles.css.scss
> +  margin-bottom: 4px;
inconsistent tab style

2017-08-10 20:13 UTC, mrgenixus commented on app/controllers/mentorships_controller.rb
> +    if @mentorship.save
vws?

2017-08-10 20:13 UTC, mrgenixus commented on app/views/mentorships/new.html.erb
> +		  <%= f.text_field :question, id: 'question-input' %>
inconsistent tab style.

2017-08-10 20:13 UTC, mrgenixus commented on spec/factories/mentorships.rb
> +    mentee_id { FactoryGirl.create(:user, :mentee, :not_on_waitlist, :any_stage_of_career, primary_industry: "Technology").id }
it's usually nice to create a 'mentee' factory and then provided these defaults for user ... should make it possible to not do this inline here.  Maybe not.  Recommend experiment

2017-08-10 20:13 UTC, mrgenixus commented on spec/factories/users.rb
> +      mentor_industry {["Business", "Technology", "Startup"].sample}
Is style here correct?

2017-08-10 20:13 UTC, mrgenixus commented on spec/factories/users.rb
> +      wants_mentor true
might be worthwhile to simply make this part of 'mentee' factory instead, see previous

2017-08-10 20:13 UTC, mrgenixus commented on spec/features/request_a_mentor_spec.rb
> +
need this ws?

2017-08-10 20:13 UTC, mrgenixus commented on spec/features/request_a_mentor_spec.rb
> +  let(:mentee) { create :user, :not_on_waitlist }
see mentee factory comment in mentorship factory `let(:mentee) { create :mentee }`

2017-08-10 20:13 UTC, mrgenixus commented on spec/models/mentorship_spec.rb
> + 			user = User.create!(email: "hellowerqerwred2@gmail.com", password: "Somethingwierd12",password_confirmation: "Somethingwierd12", first_name: "Hello",last_name: "world", mentor: true, primary_indu
this seems like you should create a specific named factory for this, rather than doing all of this, inline

2017-08-10 20:13 UTC, mrgenixus commented on spec/models/user_spec.rb
> +    it "returns all mentors" do
I like a ws before to set off the 'it', but ymmv

2017-08-10 20:13 UTC, mrgenixus commented on spec/support/shared_context/rake.rb
> +shared_context "rake" do
pulled from thoughbot?

2017-08-10 21:11 UTC, rfjackson11 commented on spec/support/shared_context/rake.rb
> +shared_context "rake" do
yep

2017-08-10 21:12 UTC, rfjackson11 commented on spec/models/mentorship_spec.rb
> + 			user = User.create!(email: "hellowerqerwred2@gmail.com", password: "Somethingwierd12",password_confirmation: "Somethingwierd12", first_name: "Hello",last_name: "world", mentor: true, primary_indu
I agree, I had not thought about it since I didn't mess with this line much, but seems like a good time to change it. Thanks 👍

2017-08-11 19:26 UTC, marshallds approved these changes

2017-08-11 19:26 UTC, marshallds commented on app/views/mentorships/new.html.erb
> +    <%end%>
ws

2017-08-11 19:26 UTC, marshallds commented on lib/tasks/womenrising.rake
> +        SlackNotification.notify(action, message)
I prefer to inline action here

2017-08-11 19:34 UTC, merged